### ISSUE TITLE
Parsing issue in windows files.

### ISSUE THREAD

**Issue by smgl9** [wavedrom/vcd#29]
Hello!

While I was testing the integration in TerosHDL and I have found this issue.
I have generated an VDC with ghdl for the same test in windows and linux. The linux generated file is correctly rendered, but windows' file not :(
After a quick investigation I think the issue is related with "new line" characters in windows.

I attach the generated VCDs. The results can be easily seen here: https://drom.io/vcd
[wave.zip](https://github.com/wavedrom/vcd/files/7231682/wave.zip)
/

**Comment by drom** [comment]
Ah! good point. looking into it.

**Comment by drom** [comment]
fixed in v0.15.3

**Comment by smgl9** [comment]
Thank you!!
I'll provide a bunch of files generated in Windows

**Comment by drom** [comment]
I have found some of VCD files failing in https://github.com/wavedrom/vcd-samples was because of Windows EOL.
